<?php

const TAXONOMYENGINE_DB_VERSION = 0.11;
const TAXONOMYENGINE_REVIEWER_ROLE = "taxonomyengine-reviewer";
const TAXONOMYENGINE_REVIEWER_ROLE_NAME = "TaxonomyEngine Reviewer";
const TAXONOMYENGINE_DEFAULT_STARTING_WEIGHT = 0.1;
const TAXONOMYENGINE_DEFAULT_DATASET_NAME = "taxonomyengine";