<?php

const TAXONOMYENGINE_DB_VERSION = 0.10;
const TAXONOMYENGINE_REVIEWER_ROLE = "taxonomyengine-reveiwer";
const TAXONOMYENGINE_REVIEWER_ROLE_NAME = "TaxonomyEngine Reviewer";
const TAXONOMYENGINE_DEFAULT_STARTING_WEIGHT = 0.1;

?>